### ISSUE TITLE
Change clefs displayed too large, and key signatures get misplaced when staff size is modified

### ISSUE THREAD

**Issue by vanleefxp** [tr-igem/esmuflily#12]
Can size or other parameters of specific characters be changed with Ekmelos? When using my own SMuFL music font I found that the change clefs are displayed overly large and accidentals in key signatures get misplaced.

For example in the following score sample, I've adjusted the staff size to be smaller in my layout settings by setting `\override Score.StaffSymbol.staff-space = #0.85`, and as a result, the flat signs in the key signature above / below the middle staff line goes slightly too up / down. The key signature problem also occurs in `openlilylib`'s `smufl` library.

Also, the change clefs are almost the same size as ordinary clefs, which is not compatible with the actual glyph size in the SMuFL font. The two clef glyphs' actual size in FontForge are displayed below the sample score.

Sample score using `esmuflily`:

![](https://github.com/user-attachments/assets/651b7607-bd63-42fe-932b-4250675523e6)

Sample score using `openlilylib`'s `smufl` library, with key signature positions adjusted by changing a parameter in the source file (but problems will still occur if `Score.StaffSymbol.staff-space` gets changed):

![](https://github.com/user-attachments/assets/e56bfc66-e031-4a5f-949e-9bac9367755c)

Ordinary and change treble clef glyph size in FontForge:

![](https://github.com/user-attachments/assets/25d251e2-d4d7-4ae9-b77e-bae934945a56)
![](https://github.com/user-attachments/assets/cb77a470-637f-43c6-a086-e8d96552695f)

**Comment by tr-igem** [comment]
I tried the following minimal working example with the fonts Bravura and Ekmelos, using three alternatives (A, B, C) to change the staff size.  The first one with `set-global-staff-size` gives the desired result, but not the other two placed in the layout block.
I have currently no explanation for the wrong size of the change clefs.  The wrong vertical position of key signature accidentals is an [issue in ekmelily](https://github.com/tr-igem/ekmelily/issues/8) (hope I can fix it soon).

    \version "2.24.0"
    ekmFont = "Bravura"
    \include "esmufl.ily"
    \include "ekmel-24.ily"
    #(set-global-staff-size 17)  %%  (A)
    \score {
      \relative c {
        \key as \major
        \clef F es as a es~ es as a \clef G f'~ f c'2 f,4 ges c2 g4 \clef F R1
      }
      \layout {
        % #(layout-set-staff-size 17)  %%  (B)
        \context {
          \Score
          \ekmSmuflOn #'all
          % \override StaffSymbol.staff-space = #0.85  %%  (C)
        }
      }
    }

**Comment by vanleefxp** [comment]
Thanks for the explanation. I have never tried using the `set-global-staff-size` command to set staff size before.  I'll try it later on.
